<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>manipulator_teleop</name>
  <version>1.0.0</version>
  <description>Real-Time Cartesian Teleoperation, State Machine, and Benchmarking</description>
  <maintainer email="engineer@robotics.dev">CVSP Engineer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>moveit_servo</exec_depend>
  <exec_depend>manipulator_moveit_config</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
